language: go
go:
    - 1.10.x
    - 1.11.x
    - 1.12.x
before_install:
    - sudo apt update
    - sudo apt install libpcap-dev
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
install:
    - go get github.com/xtaci/kcptun/client
    - go get github.com/xtaci/kcptun/server
before_script:
script:
    - cd $HOME/gopath/src/github.com/xtaci/kcptun/client
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - cd $HOME/gopath/src/github.com/xtaci/kcptun/server
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - exit 0
